# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Keelson contributors (Fred Cooke)

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${ProjectName}-role-checksum
  namespace: ${Environment}
  labels:
    kaptain.org/environment: ${Environment}
    kaptain.org/product: ${ProductName}
    kaptain.org/project-name: ${ProjectName}
    kaptain.org/version: "${Version}"
    kaptain.org/owner: ${RepositoryOwner}
    app.kubernetes.io/name: ${ProjectName}
    app.kubernetes.io/instance: ${ProjectName}
    app.kubernetes.io/version: "${Version}"
    app.kubernetes.io/managed-by: Kaptain
    app: ${ProjectName}
    app.kubernetes.io/part-of: ${ProductName}
  annotations:
    kaptain.org/source-repository: ${RepositoryOwner}/${RepositoryName}
rules:
  # Index 0
  # For kubernetes.io/dockerconfigjson Secrets: workload/SA imagePullSecrets and registry-wide ones
  # Remove if using aws-irsa, azure-wi, gcp-wi, or their synonyms exclusively
  # Narrow by specifying resourceNames if you know the list up front
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

  # Index 1
  # Workload ServiceAccounts for when KEELSON_RESPECT_SA_PULL_SECRETS is true
  # Remove if KEELSON_RESPECT_SA_PULL_SECRETS is false
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get"]

  # Index 2
  # For updating images on Deployments
  # Remove if you don't need Deployments watched
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]

  # Index 3
  # For updating images on StatefulSets
  # Remove if you don't need StatefulSets watched
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "patch", "update"]

  # Index 4
  # For updating images on DaemonSets
  # Remove if you don't need DaemonSets watched
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get", "list", "watch", "patch", "update"]

  # Index 5
  # For updating images on CronJobs (special suspended AND normal ones)
  # Remove if you don't need Cronjobs of either type watched
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "watch", "patch", "update"]

  # Index 6
  # For creating one-off Jobs from CronJobs
  # Remove if you have no special suspended CronJobs
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create"]
